/*
  ~ Copyright (c) 2020 - NOW wldos.com. All rights reserved.
  ~ Licensed under the Apache License Version 2.0 or a commercial license.
  ~ For Apache License Version 2.0 see License in the project root for license information.
  ~ For commercial licenses see term.md or https://www.wldos.com
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wldos_dll_Operation */
#include <stdio.h>
#include <stdarg.h>
#ifndef _Included_com_wldos_dll_Operation
#define _Included_com_wldos_dll_Operation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wldos_dll_Operation
 * Method:    add
 * Signature: (II)I
 */
EXPORT jint CONICAL Java_com_zd_bx_Operation_add
  (JNIEnv *, object, jint, jint);

#ifdef __cplusplus
}
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

/*
 * JNI Types
 */

#ifndef JNI_TYPES_ALREADY_DEFINED_IN_JNI_MD_H

typedef unsigned char   jBoolean;
typedef unsigned short  jChar;
typedef short           jShort;
typedef float           jFloat;
typedef double          jDouble;

typedef jint            jSize;

#ifdef __cplusplus

class _jobject {};
class _jclass : public _jobject {};
class _jthrowable : public _jobject {};
class _jstring : public _jobject {};
class _jarray : public _jobject {};
class _jbooleanArray : public _jarray {};
class _jbyteArray : public _jarray {};
class _jcharArray : public _jarray {};
class _jshortArray : public _jarray {};
class _jintArray : public _jarray {};
class _jlongArray : public _jarray {};
class _jfloatArray : public _jarray {};
class _jdoubleArray : public _jarray {};
class _jobjectArray : public _jarray {};

typedef _jobject *jobject;
typedef _jclass *jclass;
typedef _jthrowable *jthrowable;
typedef _jstring *jstring;
typedef _jarray *jarray;
typedef _jbooleanArray *jbooleanArray;
typedef _jbyteArray *jbyteArray;
typedef _jcharArray *jcharArray;
typedef _jshortArray *jshortArray;
typedef _jintArray *jintArray;
typedef _jlongArray *jlongArray;
typedef _jfloatArray *jfloatArray;
typedef _jdoubleArray *jdoubleArray;
typedef _jobjectArray *jobjectArray;

#else

struct _jobject;

typedef struct _jobject *jobject;
typedef jobject jclass;
typedef jobject jthrowable;
typedef jobject jstring;
typedef jobject jarray;
typedef jarray jbooleanArray;
typedef jarray jbyteArray;
typedef jarray jcharArray;
typedef jarray jshortArray;
typedef jarray jintArray;
typedef jarray jlongArray;
typedef jarray jfloatArray;
typedef jarray jdoubleArray;
typedef jarray jobjectArray;

#endif

typedef jobject jweak;

typedef union jvalue {
    jBoolean z;
    jbyte    b;
    jChar    c;
    jShort   s;
    jint     i;
    jlong    j;
    jFloat   f;
    jDouble  d;
    jobject  l;
} jvalue;

struct _jfieldID;
typedef struct _jfieldID *jfieldID;

struct _jmethodID;
typedef struct _jmethodID *jmethodID;

/* Return values from jobjectRefType */
typedef enum _jobjectType {
     JNIInvalidRefType    = 0,
     JNILocalRefType      = 1,
     JNIGlobalRefType     = 2,
     JNIWeakGlobalRefType = 3
} jobjectRefType;


#endif /* JNI_TYPES_ALREADY_DEFINED_IN_JNI_MD_H */

/*
 * jBoolean constants
 */

#define JNI_FALSE 0
#define JNI_TRUE 1

/*
 * possible return values for JNI functions.
 */

#define JNI_OK           0                 /* success */
#define JNI_ERR          (-1)              /* unknown error */
#define JNI_EDETACHED    (-2)              /* thread detached from the VM */
#define JNI_EVERSION     (-3)              /* JNI version error */
#define JNI_ENOMEM       (-4)              /* not enough memory */
#define JNI_EEXIST       (-5)              /* VM already created */
#define JNI_EINVAL       (-6)              /* invalid arguments */

/*
 * used in ReleaseScalarArrayElements
 */

#define JNI_COMMIT 1
#define JNI_ABORT 2

/*
 * used in RegisterNatives to describe native method name, signature,
 * and function pointer.
 */

typedef struct {
    char *name;
    char *signature;
    void *fnPtr;
} JNINativeMethod;

/*
 * JNI Native Method Interface.
 */

struct JNINativeInterface_;

struct JNIEnv_;

#ifdef __cplusplus
typedef JNIEnv_ JNIEnv;
#else
typedef const struct JNINativeInterface_ *JNIEnv;
#endif

/*
 * JNI Invocation Interface.
 */

struct JNIInvokeInterface_;

struct JavaVM_;

#ifdef __cplusplus
typedef JavaVM_ JavaVM;
#else
typedef const struct JNIInvokeInterface_ *JavaVM;
#endif

struct JNINativeInterface_ {
    void *reserved0;
    void *reserved1;
    void *reserved2;

    void *reserved3;
    jint (JNICALL *GetVersion)(JNIEnv *env);

    jclass (JNICALL *DefineClass)
      (JNIEnv *env, const char *name, jobject loader, const jbyte *buf,
       jSize len);
    jclass (JNICALL *FindClass)
      (JNIEnv *env, const char *name);

    jmethodID (JNICALL *FromReflectedMethod)
      (JNIEnv *env, jobject method);
    jfieldID (JNICALL *FromReflectedField)
      (JNIEnv *env, jobject field);

    jobject (JNICALL *ToReflectedMethod)
      (JNIEnv *env, jclass cls, jmethodID method, jBoolean isStatic);

    jclass (JNICALL *GetSuperclass)
      (JNIEnv *env, jclass sub);
    jBoolean (JNICALL *IsAssignableFrom)
      (JNIEnv *env, jclass sub, jclass sup);

    jobject (JNICALL *ToReflectedField)
      (JNIEnv *env, jclass cls, jfieldID fieldID, jBoolean isStatic);

    jint (JNICALL *Throw)
      (JNIEnv *env, jthrowable obj);
    jint (JNICALL *ThrowNew)
      (JNIEnv *env, jclass clazz, const char *msg);
    jthrowable (JNICALL *ExceptionOccurred)
      (JNIEnv *env);
    void (JNICALL *ExceptionDescribe)
      (JNIEnv *env);
    void (JNICALL *ExceptionClear)
      (JNIEnv *env);
    void (JNICALL *FatalError)
      (JNIEnv *env, const char *msg);

    jint (JNICALL *PushLocalFrame)
      (JNIEnv *env, jint capacity);
    jobject (JNICALL *PopLocalFrame)
      (JNIEnv *env, jobject result);

    jobject (JNICALL *NewGlobalRef)
      (JNIEnv *env, jobject lobj);
    void (JNICALL *DeleteGlobalRef)
      (JNIEnv *env, jobject gref);
    void (JNICALL *DeleteLocalRef)
      (JNIEnv *env, jobject obj);
    jBoolean (JNICALL *IsSameObject)
      (JNIEnv *env, jobject obj1, jobject obj2);
    jobject (JNICALL *NewLocalRef)
      (JNIEnv *env, jobject ref);
    jint (JNICALL *EnsureLocalCapacity)
      (JNIEnv *env, jint capacity);

    jobject (JNICALL *AllocObject)
      (JNIEnv *env, jclass clazz);
    jobject (JNICALL *NewObject)
      (JNIEnv *env, jclass clazz, jmethodID method, ...);
    jobject (JNICALL *NewObjectV)
      (JNIEnv *env, jclass clazz, jmethodID method, va_list args);
    jobject (JNICALL *NewObjectA)
      (JNIEnv *env, jclass clazz, jmethodID method, const jvalue *args);

    jclass (JNICALL *GetObjectClass)
      (JNIEnv *env, jobject obj);
    jBoolean (JNICALL *IsInstanceOf)
      (JNIEnv *env, jobject obj, jclass clazz);

    jmethodID (JNICALL *GetMethodID)
      (JNIEnv *env, jclass clazz, const char *name, const char *sig);

    jobject (JNICALL *CallObjectMethod)
      (JNIEnv *env, jobject obj, jmethodID method, ...);
    jobject (JNICALL *CallObjectMethodV)
      (JNIEnv *env, jobject obj, jmethodID method, va_list args);
    jobject (JNICALL *CallObjectMethodA)
      (JNIEnv *env, jobject obj, jmethodID method, const jvalue * args);

    jBoolean (JNICALL *CallBooleanMethod)
      (JNIEnv *env, jobject obj, jmethodID method, ...);
    jBoolean (JNICALL *CallBooleanMethodV)
      (JNIEnv *env, jobject obj, jmethodID method, va_list args);
    jBoolean (JNICALL *CallBooleanMethodA)
      (JNIEnv *env, jobject obj, jmethodID method, const jvalue * args);

    jbyte (JNICALL *CallByteMethod)
      (JNIEnv *env, jobject obj, jmethodID method, ...);
    jbyte (JNICALL *CallByteMethodV)
      (JNIEnv *env, jobject obj, jmethodID method, va_list args);
    jbyte (JNICALL *CallByteMethodA)
      (JNIEnv *env, jobject obj, jmethodID method, const jvalue *args);

    jChar (JNICALL *CallCharMethod)
      (JNIEnv *env, jobject obj, jmethodID method, ...);
    jChar (JNICALL *CallCharMethodV)
      (JNIEnv *env, jobject obj, jmethodID method, va_list args);
    jChar (JNICALL *CallCharMethodA)
      (JNIEnv *env, jobject obj, jmethodID method, const jvalue *args);

    jShort (JNICALL *CallShortMethod)
      (JNIEnv *env, jobject obj, jmethodID method, ...);
    jShort (JNICALL *CallShortMethodV)
      (JNIEnv *env, jobject obj, jmethodID method, va_list args);
    jShort (JNICALL *CallShortMethodA)
      (JNIEnv *env, jobject obj, jmethodID method, const jvalue *args);

    jint (JNICALL *CallIntMethod)
      (JNIEnv *env, jobject obj, jmethodID method, ...);
    jint (JNICALL *CallIntMethodV)
      (JNIEnv *env, jobject obj, jmethodID method, va_list args);
    jint (JNICALL *CallIntMethodA)
      (JNIEnv *env, jobject obj, jmethodID method, const jvalue *args);

    jlong (JNICALL *CallLongMethod)
      (JNIEnv *env, jobject obj, jmethodID method, ...);
    jlong (JNICALL *CallLongMethodV)
      (JNIEnv *env, jobject obj, jmethodID method, va_list args);
    jlong (JNICALL *CallLongMethodA)
      (JNIEnv *env, jobject obj, jmethodID method, const jvalue *args);

    jFloat (JNICALL *CallFloatMethod)
      (JNIEnv *env, jobject obj, jmethodID method, ...);
    jFloat (JNICALL *CallFloatMethodV)
      (JNIEnv *env, jobject obj, jmethodID method, va_list args);
    jFloat (JNICALL *CallFloatMethodA)
      (JNIEnv *env, jobject obj, jmethodID method, const jvalue *args);

    jDouble (JNICALL *CallDoubleMethod)
      (JNIEnv *env, jobject obj, jmethodID method, ...);
    jDouble (JNICALL *CallDoubleMethodV)
      (JNIEnv *env, jobject obj, jmethodID method, va_list args);
    jDouble (JNICALL *CallDoubleMethodA)
      (JNIEnv *env, jobject obj, jmethodID method, const jvalue *args);

    void (JNICALL *CallVoidMethod)
      (JNIEnv *env, jobject obj, jmethodID method, ...);
    void (JNICALL *CallVoidMethodV)
      (JNIEnv *env, jobject obj, jmethodID method, va_list args);
    void (JNICALL *CallVoidMethodA)
      (JNIEnv *env, jobject obj, jmethodID method, const jvalue * args);

    jobject (JNICALL *CallNonvirtualObjectMethod)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method, ...);
    jobject (JNICALL *CallNonvirtualObjectMethodV)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       va_list args);
    jobject (JNICALL *CallNonvirtualObjectMethodA)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       const jvalue * args);

    jBoolean (JNICALL *CallNonvirtualBooleanMethod)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method, ...);
    jBoolean (JNICALL *CallNonvirtualBooleanMethodV)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       va_list args);
    jBoolean (JNICALL *CallNonvirtualBooleanMethodA)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       const jvalue * args);

    jbyte (JNICALL *CallNonvirtualByteMethod)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method, ...);
    jbyte (JNICALL *CallNonvirtualByteMethodV)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       va_list args);
    jbyte (JNICALL *CallNonvirtualByteMethodA)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       const jvalue *args);

    jChar (JNICALL *CallNonvirtualCharMethod)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method, ...);
    jChar (JNICALL *CallNonvirtualCharMethodV)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       va_list args);
    jChar (JNICALL *CallNonvirtualCharMethodA)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       const jvalue *args);

    jShort (JNICALL *CallNonvirtualShortMethod)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method, ...);
    jShort (JNICALL *CallNonvirtualShortMethodV)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       va_list args);
    jShort (JNICALL *CallNonvirtualShortMethodA)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       const jvalue *args);

    jint (JNICALL *CallNonvirtualIntMethod)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method, ...);
    jint (JNICALL *CallNonvirtualIntMethodV)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       va_list args);
    jint (JNICALL *CallNonvirtualIntMethodA)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       const jvalue *args);

    jlong (JNICALL *CallNonvirtualLongMethod)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method, ...);
    jlong (JNICALL *CallNonvirtualLongMethodV)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       va_list args);
    jlong (JNICALL *CallNonvirtualLongMethodA)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       const jvalue *args);

    jFloat (JNICALL *CallNonvirtualFloatMethod)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method, ...);
    jFloat (JNICALL *CallNonvirtualFloatMethodV)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       va_list args);
    jFloat (JNICALL *CallNonvirtualFloatMethodA)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       const jvalue *args);

    jDouble (JNICALL *CallNonvirtualDoubleMethod)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method, ...);
    jDouble (JNICALL *CallNonvirtualDoubleMethodV)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       va_list args);
    jDouble (JNICALL *CallNonvirtualDoubleMethodA)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       const jvalue *args);

    void (JNICALL *CallNonvirtualVoidMethod)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method, ...);
    void (JNICALL *CallNonvirtualVoidMethodV)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       va_list args);
    void (JNICALL *CallNonvirtualVoidMethodA)
      (JNIEnv *env, jobject obj, jclass clazz, jmethodID method,
       const jvalue * args);

    jfieldID (JNICALL *GetFieldID)
      (JNIEnv *env, jclass clazz, const char *name, const char *sig);

    jobject (JNICALL *GetObjectField)
      (JNIEnv *env, jobject obj, jfieldID fieldID);
    jBoolean (JNICALL *GetBooleanField)
      (JNIEnv *env, jobject obj, jfieldID fieldID);
    jbyte (JNICALL *GetByteField)
      (JNIEnv *env, jobject obj, jfieldID fieldID);
    jChar (JNICALL *GetCharField)
      (JNIEnv *env, jobject obj, jfieldID fieldID);
    jShort (JNICALL *GetShortField)
      (JNIEnv *env, jobject obj, jfieldID fieldID);
    jint (JNICALL *GetIntField)
      (JNIEnv *env, jobject obj, jfieldID fieldID);
    jlong (JNICALL *GetLongField)
      (JNIEnv *env, jobject obj, jfieldID fieldID);
    jFloat (JNICALL *GetFloatField)
      (JNIEnv *env, jobject obj, jfieldID fieldID);
    jDouble (JNICALL *GetDoubleField)
      (JNIEnv *env, jobject obj, jfieldID fieldID);

    void (JNICALL *SetObjectField)
      (JNIEnv *env, jobject obj, jfieldID fieldID, jobject val);
    void (JNICALL *SetBooleanField)
      (JNIEnv *env, jobject obj, jfieldID fieldID, jBoolean val);
    void (JNICALL *SetByteField)
      (JNIEnv *env, jobject obj, jfieldID fieldID, jbyte val);
    void (JNICALL *SetCharField)
      (JNIEnv *env, jobject obj, jfieldID fieldID, jChar val);
    void (JNICALL *SetShortField)
      (JNIEnv *env, jobject obj, jfieldID fieldID, jShort val);
    void (JNICALL *SetIntField)
      (JNIEnv *env, jobject obj, jfieldID fieldID, jint val);
    void (JNICALL *SetLongField)
      (JNIEnv *env, jobject obj, jfieldID fieldID, jlong val);
    void (JNICALL *SetFloatField)
      (JNIEnv *env, jobject obj, jfieldID fieldID, jFloat val);
    void (JNICALL *SetDoubleField)
      (JNIEnv *env, jobject obj, jfieldID fieldID, jDouble val);

    jmethodID (JNICALL *GetStaticMethodID)
      (JNIEnv *env, jclass clazz, const char *name, const char *sig);

    jobject (JNICALL *CallStaticObjectMethod)
      (JNIEnv *env, jclass clazz, jmethodID method, ...);
    jobject (JNICALL *CallStaticObjectMethodV)
      (JNIEnv *env, jclass clazz, jmethodID method, va_list args);
    jobject (JNICALL *CallStaticObjectMethodA)
      (JNIEnv *env, jclass clazz, jmethodID method, const jvalue *args);

    jBoolean (JNICALL *CallStaticBooleanMethod)
      (JNIEnv *env, jclass clazz, jmethodID method, ...);
    jBoolean (JNICALL *CallStaticBooleanMethodV)
      (JNIEnv *env, jclass clazz, jmethodID method, va_list args);
    jBoolean (JNICALL *CallStaticBooleanMethodA)
      (JNIEnv *env, jclass clazz, jmethodID method, const jvalue *args);

    jbyte (JNICALL *CallStaticByteMethod)
      (JNIEnv *env, jclass clazz, jmethodID method, ...);
    jbyte (JNICALL *CallStaticByteMethodV)
      (JNIEnv *env, jclass clazz, jmethodID method, va_list args);
    jbyte (JNICALL *CallStaticByteMethodA)
      (JNIEnv *env, jclass clazz, jmethodID method, const jvalue *args);

    jChar (JNICALL *CallStaticCharMethod)
      (JNIEnv *env, jclass clazz, jmethodID method, ...);
    jChar (JNICALL *CallStaticCharMethodV)
      (JNIEnv *env, jclass clazz, jmethodID method, va_list args);
    jChar (JNICALL *CallStaticCharMethodA)
      (JNIEnv *env, jclass clazz, jmethodID method, const jvalue *args);

    jShort (JNICALL *CallStaticShortMethod)
      (JNIEnv *env, jclass clazz, jmethodID method, ...);
    jShort (JNICALL *CallStaticShortMethodV)
      (JNIEnv *env, jclass clazz, jmethodID method, va_list args);
    jShort (JNICALL *CallStaticShortMethodA)
      (JNIEnv *env, jclass clazz, jmethodID method, const jvalue *args);

    jint (JNICALL *CallStaticIntMethod)
      (JNIEnv *env, jclass clazz, jmethodID method, ...);
    jint (JNICALL *CallStaticIntMethodV)
      (JNIEnv *env, jclass clazz, jmethodID method, va_list args);
    jint (JNICALL *CallStaticIntMethodA)
      (JNIEnv *env, jclass clazz, jmethodID method, const jvalue *args);

    jlong (JNICALL *CallStaticLongMethod)
      (JNIEnv *env, jclass clazz, jmethodID method, ...);
    jlong (JNICALL *CallStaticLongMethodV)
      (JNIEnv *env, jclass clazz, jmethodID method, va_list args);
    jlong (JNICALL *CallStaticLongMethodA)
      (JNIEnv *env, jclass clazz, jmethodID method, const jvalue *args);

    jFloat (JNICALL *CallStaticFloatMethod)
      (JNIEnv *env, jclass clazz, jmethodID method, ...);
    jFloat (JNICALL *CallStaticFloatMethodV)
      (JNIEnv *env, jclass clazz, jmethodID method, va_list args);
    jFloat (JNICALL *CallStaticFloatMethodA)
      (JNIEnv *env, jclass clazz, jmethodID method, const jvalue *args);

    jDouble (JNICALL *CallStaticDoubleMethod)
      (JNIEnv *env, jclass clazz, jmethodID method, ...);
    jDouble (JNICALL *CallStaticDoubleMethodV)
      (JNIEnv *env, jclass clazz, jmethodID method, va_list args);
    jDouble (JNICALL *CallStaticDoubleMethodA)
      (JNIEnv *env, jclass clazz, jmethodID method, const jvalue *args);

    void (JNICALL *CallStaticVoidMethod)
      (JNIEnv *env, jclass cls, jmethodID method, ...);
    void (JNICALL *CallStaticVoidMethodV)
      (JNIEnv *env, jclass cls, jmethodID method, va_list args);
    void (JNICALL *CallStaticVoidMethodA)
      (JNIEnv *env, jclass cls, jmethodID method, const jvalue * args);

    jfieldID (JNICALL *GetStaticFieldID)
      (JNIEnv *env, jclass clazz, const char *name, const char *sig);
    jobject (JNICALL *GetStaticObjectField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID);
    jBoolean (JNICALL *GetStaticBooleanField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID);
    jbyte (JNICALL *GetStaticByteField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID);
    jChar (JNICALL *GetStaticCharField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID);
    jShort (JNICALL *GetStaticShortField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID);
    jint (JNICALL *GetStaticIntField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID);
    jlong (JNICALL *GetStaticLongField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID);
    jFloat (JNICALL *GetStaticFloatField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID);
    jDouble (JNICALL *GetStaticDoubleField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID);

    void (JNICALL *SetStaticObjectField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID, jobject value);
    void (JNICALL *SetStaticBooleanField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID, jBoolean value);
    void (JNICALL *SetStaticByteField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID, jbyte value);
    void (JNICALL *SetStaticCharField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID, jChar value);
    void (JNICALL *SetStaticShortField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID, jShort value);
    void (JNICALL *SetStaticIntField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID, jint value);
    void (JNICALL *SetStaticLongField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID, jlong value);
    void (JNICALL *SetStaticFloatField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID, jFloat value);
    void (JNICALL *SetStaticDoubleField)
      (JNIEnv *env, jclass clazz, jfieldID fieldID, jDouble value);

    jstring (JNICALL *NewString)
      (JNIEnv *env, const jChar *unicode, jSize len);
    jSize (JNICALL *GetStringLength)
      (JNIEnv *env, jstring str);
    const jChar *(JNICALL *GetStringChars)
      (JNIEnv *env, jstring str, jBoolean *isCopy);
    void (JNICALL *ReleaseStringChars)
      (JNIEnv *env, jstring str, const jChar *chars);

    jstring (JNICALL *NewStringUTF)
      (JNIEnv *env, const char *utf);
    jSize (JNICALL *GetStringUTFLength)
      (JNIEnv *env, jstring str);
    const char* (JNICALL *GetStringUTFChars)
      (JNIEnv *env, jstring str, jBoolean *isCopy);
    void (JNICALL *ReleaseStringUTFChars)
      (JNIEnv *env, jstring str, const char* chars);


    jSize (JNICALL *GetArrayLength)
      (JNIEnv *env, jarray array);

    jobjectArray (JNICALL *NewObjectArray)
      (JNIEnv *env, jSize len, jclass clazz, jobject init);
    jobject (JNICALL *GetObjectArrayElement)
      (JNIEnv *env, jobjectArray array, jSize index);
    void (JNICALL *SetObjectArrayElement)
      (JNIEnv *env, jobjectArray array, jSize index, jobject val);

    jbooleanArray (JNICALL *NewBooleanArray)
      (JNIEnv *env, jSize len);
    jbyteArray (JNICALL *NewByteArray)
      (JNIEnv *env, jSize len);
    jcharArray (JNICALL *NewCharArray)
      (JNIEnv *env, jSize len);
    jshortArray (JNICALL *NewShortArray)
      (JNIEnv *env, jSize len);
    jintArray (JNICALL *NewIntArray)
      (JNIEnv *env, jSize len);
    jlongArray (JNICALL *NewLongArray)
      (JNIEnv *env, jSize len);
    jfloatArray (JNICALL *NewFloatArray)
      (JNIEnv *env, jSize len);
    jdoubleArray (JNICALL *NewDoubleArray)
      (JNIEnv *env, jSize len);

    jBoolean * (JNICALL *GetBooleanArrayElements)
      (JNIEnv *env, jbooleanArray array, jBoolean *isCopy);
    jbyte * (JNICALL *GetByteArrayElements)
      (JNIEnv *env, jbyteArray array, jBoolean *isCopy);
    jChar * (JNICALL *GetCharArrayElements)
      (JNIEnv *env, jcharArray array, jBoolean *isCopy);
    jShort * (JNICALL *GetShortArrayElements)
      (JNIEnv *env, jshortArray array, jBoolean *isCopy);
    jint * (JNICALL *GetIntArrayElements)
      (JNIEnv *env, jintArray array, jBoolean *isCopy);
    jlong * (JNICALL *GetLongArrayElements)
      (JNIEnv *env, jlongArray array, jBoolean *isCopy);
    jFloat * (JNICALL *GetFloatArrayElements)
      (JNIEnv *env, jfloatArray array, jBoolean *isCopy);
    jDouble * (JNICALL *GetDoubleArrayElements)
      (JNIEnv *env, jdoubleArray array, jBoolean *isCopy);

    void (JNICALL *ReleaseBooleanArrayElements)
      (JNIEnv *env, jbooleanArray array, jBoolean *elems, jint mode);
    void (JNICALL *ReleaseByteArrayElements)
      (JNIEnv *env, jbyteArray array, jbyte *elems, jint mode);
    void (JNICALL *ReleaseCharArrayElements)
      (JNIEnv *env, jcharArray array, jChar *elems, jint mode);
    void (JNICALL *ReleaseShortArrayElements)
      (JNIEnv *env, jshortArray array, jShort *elems, jint mode);
    void (JNICALL *ReleaseIntArrayElements)
      (JNIEnv *env, jintArray array, jint *elems, jint mode);
    void (JNICALL *ReleaseLongArrayElements)
      (JNIEnv *env, jlongArray array, jlong *elems, jint mode);
    void (JNICALL *ReleaseFloatArrayElements)
      (JNIEnv *env, jfloatArray array, jFloat *elems, jint mode);
    void (JNICALL *ReleaseDoubleArrayElements)
      (JNIEnv *env, jdoubleArray array, jDouble *elems, jint mode);

    void (JNICALL *GetBooleanArrayRegion)
      (JNIEnv *env, jbooleanArray array, jSize start, jSize l, jBoolean *buf);
    void (JNICALL *GetByteArrayRegion)
      (JNIEnv *env, jbyteArray array, jSize start, jSize len, jbyte *buf);
    void (JNICALL *GetCharArrayRegion)
      (JNIEnv *env, jcharArray array, jSize start, jSize len, jChar *buf);
    void (JNICALL *GetShortArrayRegion)
      (JNIEnv *env, jshortArray array, jSize start, jSize len, jShort *buf);
    void (JNICALL *GetIntArrayRegion)
      (JNIEnv *env, jintArray array, jSize start, jSize len, jint *buf);
    void (JNICALL *GetLongArrayRegion)
      (JNIEnv *env, jlongArray array, jSize start, jSize len, jlong *buf);
    void (JNICALL *GetFloatArrayRegion)
      (JNIEnv *env, jfloatArray array, jSize start, jSize len, jFloat *buf);
    void (JNICALL *GetDoubleArrayRegion)
      (JNIEnv *env, jdoubleArray array, jSize start, jSize len, jDouble *buf);

    void (JNICALL *SetBooleanArrayRegion)
      (JNIEnv *env, jbooleanArray array, jSize start, jSize l, const jBoolean *buf);
    void (JNICALL *SetByteArrayRegion)
      (JNIEnv *env, jbyteArray array, jSize start, jSize len, const jbyte *buf);
    void (JNICALL *SetCharArrayRegion)
      (JNIEnv *env, jcharArray array, jSize start, jSize len, const jChar *buf);
    void (JNICALL *SetShortArrayRegion)
      (JNIEnv *env, jshortArray array, jSize start, jSize len, const jShort *buf);
    void (JNICALL *SetIntArrayRegion)
      (JNIEnv *env, jintArray array, jSize start, jSize len, const jint *buf);
    void (JNICALL *SetLongArrayRegion)
      (JNIEnv *env, jlongArray array, jSize start, jSize len, const jlong *buf);
    void (JNICALL *SetFloatArrayRegion)
      (JNIEnv *env, jfloatArray array, jSize start, jSize len, const jFloat *buf);
    void (JNICALL *SetDoubleArrayRegion)
      (JNIEnv *env, jdoubleArray array, jSize start, jSize len, const jDouble *buf);

    jint (JNICALL *RegisterNatives)
      (JNIEnv *env, jclass clazz, const JNINativeMethod *methods,
       jint nMethods);
    jint (JNICALL *UnregisterNatives)
      (JNIEnv *env, jclass clazz);

    jint (JNICALL *MonitorEnter)
      (JNIEnv *env, jobject obj);
    jint (JNICALL *MonitorExit)
      (JNIEnv *env, jobject obj);

    jint (JNICALL *GetJavaVM)
      (JNIEnv *env, JavaVM **vm);

    void (JNICALL *GetStringRegion)
      (JNIEnv *env, jstring str, jSize start, jSize len, jChar *buf);
    void (JNICALL *GetStringUTFRegion)
      (JNIEnv *env, jstring str, jSize start, jSize len, char *buf);

    void * (JNICALL *GetPrimitiveArrayCritical)
      (JNIEnv *env, jarray array, jBoolean *isCopy);
    void (JNICALL *ReleasePrimitiveArrayCritical)
      (JNIEnv *env, jarray array, void *carray, jint mode);

    const jChar * (JNICALL *GetStringCritical)
      (JNIEnv *env, jstring string, jBoolean *isCopy);
    void (JNICALL *ReleaseStringCritical)
      (JNIEnv *env, jstring string, const jChar *cstring);

    jweak (JNICALL *NewWeakGlobalRef)
       (JNIEnv *env, jobject obj);
    void (JNICALL *DeleteWeakGlobalRef)
       (JNIEnv *env, jweak ref);

    jBoolean (JNICALL *ExceptionCheck)
       (JNIEnv *env);

    jobject (JNICALL *NewDirectByteBuffer)
       (JNIEnv* env, void* address, jlong capacity);
    void* (JNICALL *GetDirectBufferAddress)
       (JNIEnv* env, jobject buf);
    jlong (JNICALL *GetDirectBufferCapacity)
       (JNIEnv* env, jobject buf);

    /* New JNI 1.6 Features */

    jobjectRefType (JNICALL *GetObjectRefType)
        (JNIEnv* env, jobject obj);
};

/*
 * We use inlined functions for C++ so that programmers can write:
 *
 *    env->FindClass("java/lang/String")
 *
 * in C++ rather than:
 *
 *    (*env)->FindClass(env, "java/lang/String")
 *
 * in C.
 */

struct JNIEnv_ {
    const struct JNINativeInterface_ *functions;
#ifdef __cplusplus

    jint GetVersion() {
        return functions->GetVersion(this);
    }
    jclass DefineClass(const char *name, jobject loader, const jbyte *buf,
                       jSize len) {
        return functions->DefineClass(this, name, loader, buf, len);
    }
    jclass FindClass(const char *name) {
        return functions->FindClass(this, name);
    }
    jmethodID FromReflectedMethod(jobject method) {
        return functions->FromReflectedMethod(this,method);
    }
    jfieldID FromReflectedField(jobject field) {
        return functions->FromReflectedField(this,field);
    }

    jobject ToReflectedMethod(jclass cls, jmethodID method, jBoolean isStatic) {
        return functions->ToReflectedMethod(this, cls, method, isStatic);
    }

    jclass GetSuperclass(jclass sub) {
        return functions->GetSuperclass(this, sub);
    }
    jBoolean IsAssignableFrom(jclass sub, jclass sup) {
        return functions->IsAssignableFrom(this, sub, sup);
    }

    jobject ToReflectedField(jclass cls, jfieldID fieldID, jBoolean isStatic) {
        return functions->ToReflectedField(this,cls,fieldID,isStatic);
    }

    jint Throw(jthrowable obj) {
        return functions->Throw(this, obj);
    }
    jint ThrowNew(jclass clazz, const char *msg) {
        return functions->ThrowNew(this, clazz, msg);
    }
    jthrowable ExceptionOccurred() {
        return functions->ExceptionOccurred(this);
    }
    void ExceptionDescribe() {
        functions->ExceptionDescribe(this);
    }
    void ExceptionClear() {
        functions->ExceptionClear(this);
    }
    void FatalError(const char *msg) {
        functions->FatalError(this, msg);
    }

    jint PushLocalFrame(jint capacity) {
        return functions->PushLocalFrame(this,capacity);
    }
    jobject PopLocalFrame(jobject result) {
        return functions->PopLocalFrame(this,result);
    }

    jobject NewGlobalRef(jobject lobj) {
        return functions->NewGlobalRef(this,lobj);
    }
    void DeleteGlobalRef(jobject gref) {
        functions->DeleteGlobalRef(this,gref);
    }
    void DeleteLocalRef(jobject obj) {
        functions->DeleteLocalRef(this, obj);
    }

    jBoolean IsSameObject(jobject obj1, jobject obj2) {
        return functions->IsSameObject(this,obj1,obj2);
    }

    jobject NewLocalRef(jobject ref) {
        return functions->NewLocalRef(this,ref);
    }
    jint EnsureLocalCapacity(jint capacity) {
        return functions->EnsureLocalCapacity(this,capacity);
    }

    jobject AllocObject(jclass clazz) {
        return functions->AllocObject(this,clazz);
    }
    jobject NewObject(jclass clazz, jmethodID method, ...) {
        va_list args;
        jobject result;
        va_start(args, method);
        result = functions->NewObjectV(this,clazz,method,args);
        va_end(args);
        return result;
    }
    jobject NewObjectV(jclass clazz, jmethodID method,
                       va_list args) {
        return functions->NewObjectV(this,clazz,method,args);
    }
    jobject NewObjectA(jclass clazz, jmethodID method,
                       const jvalue *args) {
        return functions->NewObjectA(this,clazz,method,args);
    }

    jclass GetObjectClass(jobject obj) {
        return functions->GetObjectClass(this,obj);
    }
    jBoolean IsInstanceOf(jobject obj, jclass clazz) {
        return functions->IsInstanceOf(this,obj,clazz);
    }

    jmethodID GetMethodID(jclass clazz, const char *name,
                          const char *sig) {
        return functions->GetMethodID(this,clazz,name,sig);
    }

    jobject CallObjectMethod(jobject obj, jmethodID method, ...) {
        va_list args;
        jobject result;
        va_start(args,method);
        result = functions->CallObjectMethodV(this,obj,method,args);
        va_end(args);
        return result;
    }
    jobject CallObjectMethodV(jobject obj, jmethodID method,
                        va_list args) {
        return functions->CallObjectMethodV(this,obj,method,args);
    }
    jobject CallObjectMethodA(jobject obj, jmethodID method,
                        const jvalue * args) {
        return functions->CallObjectMethodA(this,obj,method,args);
    }

    jBoolean CallBooleanMethod(jobject obj,
                               jmethodID method, ...) {
        va_list args;
        jBoolean result;
        va_start(args,method);
        result = functions->CallBooleanMethodV(this,obj,method,args);
        va_end(args);
        return result;
    }
    jBoolean CallBooleanMethodV(jobject obj, jmethodID method,
                                va_list args) {
        return functions->CallBooleanMethodV(this,obj,method,args);
    }
    jBoolean CallBooleanMethodA(jobject obj, jmethodID method,
                                const jvalue * args) {
        return functions->CallBooleanMethodA(this,obj,method, args);
    }

    jbyte CallByteMethod(jobject obj, jmethodID method, ...) {
        va_list args;
        jbyte result;
        va_start(args,method);
        result = functions->CallByteMethodV(this,obj,method,args);
        va_end(args);
        return result;
    }
    jbyte CallByteMethodV(jobject obj, jmethodID method,
                          va_list args) {
        return functions->CallByteMethodV(this,obj,method,args);
    }
    jbyte CallByteMethodA(jobject obj, jmethodID method,
                          const jvalue * args) {
        return functions->CallByteMethodA(this,obj,method,args);
    }

    jChar CallCharMethod(jobject obj, jmethodID method, ...) {
        va_list args;
        jChar result;
        va_start(args,method);
        result = functions->CallCharMethodV(this,obj,method,args);
        va_end(args);
        return result;
    }
    jChar CallCharMethodV(jobject obj, jmethodID method,
                          va_list args) {
        return functions->CallCharMethodV(this,obj,method,args);
    }
    jChar CallCharMethodA(jobject obj, jmethodID method,
                          const jvalue * args) {
        return functions->CallCharMethodA(this,obj,method,args);
    }

    jShort CallShortMethod(jobject obj, jmethodID method, ...) {
        va_list args;
        jShort result;
        va_start(args,method);
        result = functions->CallShortMethodV(this,obj,method,args);
        va_end(args);
        return result;
    }
    jShort CallShortMethodV(jobject obj, jmethodID method,
                            va_list args) {
        return functions->CallShortMethodV(this,obj,method,args);
    }
    jShort CallShortMethodA(jobject obj, jmethodID method,
                            const jvalue * args) {
        return functions->CallShortMethodA(this,obj,method,args);
    }

    jint CallIntMethod(jobject obj, jmethodID method, ...) {
        va_list args;
        jint result;
        va_start(args,method);
        result = functions->CallIntMethodV(this,obj,method,args);
        va_end(args);
        return result;
    }
    jint CallIntMethodV(jobject obj, jmethodID method,
                        va_list args) {
        return functions->CallIntMethodV(this,obj,method,args);
    }
    jint CallIntMethodA(jobject obj, jmethodID method,
                        const jvalue * args) {
        return functions->CallIntMethodA(this,obj,method,args);
    }

    jlong CallLongMethod(jobject obj, jmethodID method, ...) {
        va_list args;
        jlong result;
        va_start(args,method);
        result = functions->CallLongMethodV(this,obj,method,args);
        va_end(args);
        return result;
    }
    jlong CallLongMethodV(jobject obj, jmethodID method,
                          va_list args) {
        return functions->CallLongMethodV(this,obj,method,args);
    }
    jlong CallLongMethodA(jobject obj, jmethodID method,
                          const jvalue * args) {
        return functions->CallLongMethodA(this,obj,method,args);
    }

    jFloat CallFloatMethod(jobject obj, jmethodID method, ...) {
        va_list args;
        jFloat result;
        va_start(args,method);
        result = functions->CallFloatMethodV(this,obj,method,args);
        va_end(args);
        return result;
    }
    jFloat CallFloatMethodV(jobject obj, jmethodID method,
                            va_list args) {
        return functions->CallFloatMethodV(this,obj,method,args);
    }
    jFloat CallFloatMethodA(jobject obj, jmethodID method,
                            const jvalue * args) {
        return functions->CallFloatMethodA(this,obj,method,args);
    }

    jDouble CallDoubleMethod(jobject obj, jmethodID method, ...) {
        va_list args;
        jDouble result;
        va_start(args,method);
        result = functions->CallDoubleMethodV(this,obj,method,args);
        va_end(args);
        return result;
    }
    jDouble CallDoubleMethodV(jobject obj, jmethodID method,
                        va_list args) {
        return functions->CallDoubleMethodV(this,obj,method,args);
    }
    jDouble CallDoubleMethodA(jobject obj, jmethodID method,
                        const jvalue * args) {
        return functions->CallDoubleMethodA(this,obj,method,args);
    }

    void CallVoidMethod(jobject obj, jmethodID method, ...) {
        va_list args;
        va_start(args,method);
        functions->CallVoidMethodV(this,obj,method,args);
        va_end(args);
    }
    void CallVoidMethodV(jobject obj, jmethodID method,
                         va_list args) {
        functions->CallVoidMethodV(this,obj,method,args);
    }
    void CallVoidMethodA(jobject obj, jmethodID method,
                         const jvalue * args) {
        functions->CallVoidMethodA(this,obj,method,args);
    }

    jobject CallNonvirtualObjectMethod(jobject obj, jclass clazz,
                                       jmethodID method, ...) {
        va_list args;
        jobject result;
        va_start(args,method);
        result = functions->CallNonvirtualObjectMethodV(this,obj,clazz,
                                                        method,args);
        va_end(args);
        return result;
    }
    jobject CallNonvirtualObjectMethodV(jobject obj, jclass clazz,
                                        jmethodID method, va_list args) {
        return functions->CallNonvirtualObjectMethodV(this,obj,clazz,
                                                      method,args);
    }
    jobject CallNonvirtualObjectMethodA(jobject obj, jclass clazz,
                                        jmethodID method, const jvalue * args) {
        return functions->CallNonvirtualObjectMethodA(this,obj,clazz,
                                                      method,args);
    }

    jBoolean CallNonvirtualBooleanMethod(jobject obj, jclass clazz,
                                         jmethodID method, ...) {
        va_list args;
        jBoolean result;
        va_start(args,method);
        result = functions->CallNonvirtualBooleanMethodV(this,obj,clazz,
                                                         method,args);
        va_end(args);
        return result;
    }
    jBoolean CallNonvirtualBooleanMethodV(jobject obj, jclass clazz,
                                          jmethodID method, va_list args) {
        return functions->CallNonvirtualBooleanMethodV(this,obj,clazz,
                                                       method,args);
    }
    jBoolean CallNonvirtualBooleanMethodA(jobject obj, jclass clazz,
                                          jmethodID method, const jvalue * args) {
        return functions->CallNonvirtualBooleanMethodA(this,obj,clazz,
                                                       method, args);
    }

    jbyte CallNonvirtualByteMethod(jobject obj, jclass clazz,
                                   jmethodID method, ...) {
        va_list args;
        jbyte result;
        va_start(args,method);
        result = functions->CallNonvirtualByteMethodV(this,obj,clazz,
                                                      method,args);
        va_end(args);
        return result;
    }
    jbyte CallNonvirtualByteMethodV(jobject obj, jclass clazz,
                                    jmethodID method, va_list args) {
        return functions->CallNonvirtualByteMethodV(this,obj,clazz,
                                                    method,args);
    }
    jbyte CallNonvirtualByteMethodA(jobject obj, jclass clazz,
                                    jmethodID method, const jvalue * args) {
        return functions->CallNonvirtualByteMethodA(this,obj,clazz,
                                                    method,args);
    }

    jChar CallNonvirtualCharMethod(jobject obj, jclass clazz,
                                   jmethodID method, ...) {
        va_list args;
        jChar result;
        va_start(args,method);
        result = functions->CallNonvirtualCharMethodV(this,obj,clazz,
                                                      method,args);
        va_end(args);
        return result;
    }
    jChar CallNonvirtualCharMethodV(jobject obj, jclass clazz,
                                    jmethodID method, va_list args) {
        return functions->CallNonvirtualCharMethodV(this,obj,clazz,
                                                    method,args);
    }
    jChar CallNonvirtualCharMethodA(jobject obj, jclass clazz,
                                    jmethodID method, const jvalue * args) {
        return functions->CallNonvirtualCharMethodA(this,obj,clazz,
                                                    method,args);
    }

    jShort CallNonvirtualShortMethod(jobject obj, jclass clazz,
                                     jmethodID method, ...) {
        va_list args;
        jShort result;
        va_start(args,method);
        result = functions->CallNonvirtualShortMethodV(this,obj,clazz,
                                                       method,args);
        va_end(args);
        return result;
    }
    jShort CallNonvirtualShortMethodV(jobject obj, jclass clazz,
                                      jmethodID method, va_list args) {
        return functions->CallNonvirtualShortMethodV(this,obj,clazz,
                                                     method,args);
    }
    jShort CallNonvirtualShortMethodA(jobject obj, jclass clazz,
                                      jmethodID method, const jvalue * args) {
        return functions->CallNonvirtualShortMethodA(this,obj,clazz,
                                                     method,args);
    }

    jint CallNonvirtualIntMethod(jobject obj, jclass clazz,
                                 jmethodID method, ...) {
        va_list args;
        jint result;
        va_start(args,method);
        result = functions->CallNonvirtualIntMethodV(this,obj,clazz,
                                                     method,args);
        va_end(args);
        return result;
    }
    jint CallNonvirtualIntMethodV(jobject obj, jclass clazz,
                                  jmethodID method, va_list args) {
        return functions->CallNonvirtualIntMethodV(this,obj,clazz,
                                                   method,args);
    }
    jint CallNonvirtualIntMethodA(jobject obj, jclass clazz,
                                  jmethodID method, const jvalue * args) {
        return functions->CallNonvirtualIntMethodA(this,obj,clazz,
                                                   method,args);
    }

    jlong CallNonvirtualLongMethod(jobject obj, jclass clazz,
                                   jmethodID method, ...) {
        va_list args;
        jlong result;
        va_start(args,method);
        result = functions->CallNonvirtualLongMethodV(this,obj,clazz,
                                                      method,args);
        va_end(args);
        return result;
    }
    jlong CallNonvirtualLongMethodV(jobject obj, jclass clazz,
                                    jmethodID method, va_list args) {
        return functions->CallNonvirtualLongMethodV(this,obj,clazz,
                                                    method,args);
    }
    jlong CallNonvirtualLongMethodA(jobject obj, jclass clazz,
                                    jmethodID method, const jvalue * args) {
        return functions->CallNonvirtualLongMethodA(this,obj,clazz,
                                                    method,args);
    }

    jFloat CallNonvirtualFloatMethod(jobject obj, jclass clazz,
                                     jmethodID method, ...) {
        va_list args;
        jFloat result;
        va_start(args,method);
        result = functions->CallNonvirtualFloatMethodV(this,obj,clazz,
                                                       method,args);
        va_end(args);
        return result;
    }
    jFloat CallNonvirtualFloatMethodV(jobject obj, jclass clazz,
                                      jmethodID method,
                                      va_list args) {
        return functions->CallNonvirtualFloatMethodV(this,obj,clazz,
                                                     method,args);
    }
    jFloat CallNonvirtualFloatMethodA(jobject obj, jclass clazz,
                                      jmethodID method,
                                      const jvalue * args) {
        return functions->CallNonvirtualFloatMethodA(this,obj,clazz,
                                                     method,args);
    }

    jDouble CallNonvirtualDoubleMethod(jobject obj, jclass clazz,
                                       jmethodID method, ...) {
        va_list args;
        jDouble result;
        va_start(args,method);
        result = functions->CallNonvirtualDoubleMethodV(this,obj,clazz,
                                                        method,args);
        va_end(args);
        return result;
    }
    jDouble CallNonvirtualDoubleMethodV(jobject obj, jclass clazz,
                                        jmethodID method,
                                        va_list args) {
        return functions->CallNonvirtualDoubleMethodV(this,obj,clazz,
                                                      method,args);
    }
    jDouble CallNonvirtualDoubleMethodA(jobject obj, jclass clazz,
                                        jmethodID method,
                                        const jvalue * args) {
        return functions->CallNonvirtualDoubleMethodA(this,obj,clazz,
                                                      method,args);
    }

    void CallNonvirtualVoidMethod(jobject obj, jclass clazz,
                                  jmethodID method, ...) {
        va_list args;
        va_start(args,method);
        functions->CallNonvirtualVoidMethodV(this,obj,clazz,method,args);
        va_end(args);
    }
    void CallNonvirtualVoidMethodV(jobject obj, jclass clazz,
                                   jmethodID method,
                                   va_list args) {
        functions->CallNonvirtualVoidMethodV(this,obj,clazz,method,args);
    }
    void CallNonvirtualVoidMethodA(jobject obj, jclass clazz,
                                   jmethodID method,
                                   const jvalue * args) {
        functions->CallNonvirtualVoidMethodA(this,obj,clazz,method,args);
    }

    jfieldID GetFieldID(jclass clazz, const char *name,
                        const char *sig) {
        return functions->GetFieldID(this,clazz,name,sig);
    }

    jobject GetObjectField(jobject obj, jfieldID fieldID) {
        return functions->GetObjectField(this,obj,fieldID);
    }
    jBoolean GetBooleanField(jobject obj, jfieldID fieldID) {
        return functions->GetBooleanField(this,obj,fieldID);
    }
    jbyte GetByteField(jobject obj, jfieldID fieldID) {
        return functions->GetByteField(this,obj,fieldID);
    }
    jChar GetCharField(jobject obj, jfieldID fieldID) {
        return functions->GetCharField(this,obj,fieldID);
    }
    jShort GetShortField(jobject obj, jfieldID fieldID) {
        return functions->GetShortField(this,obj,fieldID);
    }
    jint GetIntField(jobject obj, jfieldID fieldID) {
        return functions->GetIntField(this,obj,fieldID);
    }
    jlong GetLongField(jobject obj, jfieldID fieldID) {
        return functions->GetLongField(this,obj,fieldID);
    }
    jFloat GetFloatField(jobject obj, jfieldID fieldID) {
        return functions->GetFloatField(this,obj,fieldID);
    }
    jDouble GetDoubleField(jobject obj, jfieldID fieldID) {
        return functions->GetDoubleField(this,obj,fieldID);
    }

    void SetObjectField(jobject obj, jfieldID fieldID, jobject val) {
        functions->SetObjectField(this,obj,fieldID,val);
    }
    void SetBooleanField(jobject obj, jfieldID fieldID,
                         jBoolean val) {
        functions->SetBooleanField(this,obj,fieldID,val);
    }
    void SetByteField(jobject obj, jfieldID fieldID,
                      jbyte val) {
        functions->SetByteField(this,obj,fieldID,val);
    }
    void SetCharField(jobject obj, jfieldID fieldID,
                      jChar val) {
        functions->SetCharField(this,obj,fieldID,val);
    }
    void SetShortField(jobject obj, jfieldID fieldID,
                       jShort val) {
        functions->SetShortField(this,obj,fieldID,val);
    }
    void SetIntField(jobject obj, jfieldID fieldID,
                     jint val) {
        functions->SetIntField(this,obj,fieldID,val);
    }
    void SetLongField(jobject obj, jfieldID fieldID,
                      jlong val) {
        functions->SetLongField(this,obj,fieldID,val);
    }
    void SetFloatField(jobject obj, jfieldID fieldID,
                       jFloat val) {
        functions->SetFloatField(this,obj,fieldID,val);
    }
    void SetDoubleField(jobject obj, jfieldID fieldID,
                        jDouble val) {
        functions->SetDoubleField(this,obj,fieldID,val);
    }

    jmethodID GetStaticMethodID(jclass clazz, const char *name,
                                const char *sig) {
        return functions->GetStaticMethodID(this,clazz,name,sig);
    }

    jobject CallStaticObjectMethod(jclass clazz, jmethodID method,
                             ...) {
        va_list args;
        jobject result;
        va_start(args,method);
        result = functions->CallStaticObjectMethodV(this,clazz,method,args);
        va_end(args);
        return result;
    }
    jobject CallStaticObjectMethodV(jclass clazz, jmethodID method,
                              va_list args) {
        return functions->CallStaticObjectMethodV(this,clazz,method,args);
    }
    jobject CallStaticObjectMethodA(jclass clazz, jmethodID method,
                              const jvalue *args) {
        return functions->CallStaticObjectMethodA(this,clazz,method,args);
    }

    jBoolean CallStaticBooleanMethod(jclass clazz,
                                     jmethodID method, ...) {
        va_list args;
        jBoolean result;
        va_start(args,method);
        result = functions->CallStaticBooleanMethodV(this,clazz,method,args);
        va_end(args);
        return result;
    }
    jBoolean CallStaticBooleanMethodV(jclass clazz,
                                      jmethodID method, va_list args) {
        return functions->CallStaticBooleanMethodV(this,clazz,method,args);
    }
    jBoolean CallStaticBooleanMethodA(jclass clazz,
                                      jmethodID method, const jvalue *args) {
        return functions->CallStaticBooleanMethodA(this,clazz,method,args);
    }

    jbyte CallStaticByteMethod(jclass clazz,
                               jmethodID method, ...) {
        va_list args;
        jbyte result;
        va_start(args,method);
        result = functions->CallStaticByteMethodV(this,clazz,method,args);
        va_end(args);
        return result;
    }
    jbyte CallStaticByteMethodV(jclass clazz,
                                jmethodID method, va_list args) {
        return functions->CallStaticByteMethodV(this,clazz,method,args);
    }
    jbyte CallStaticByteMethodA(jclass clazz,
                                jmethodID method, const jvalue *args) {
        return functions->CallStaticByteMethodA(this,clazz,method,args);
    }

    jChar CallStaticCharMethod(jclass clazz,
                               jmethodID method, ...) {
        va_list args;
        jChar result;
        va_start(args,method);
        result = functions->CallStaticCharMethodV(this,clazz,method,args);
        va_end(args);
        return result;
    }
    jChar CallStaticCharMethodV(jclass clazz,
                                jmethodID method, va_list args) {
        return functions->CallStaticCharMethodV(this,clazz,method,args);
    }
    jChar CallStaticCharMethodA(jclass clazz,
                                jmethodID method, const jvalue *args) {
        return functions->CallStaticCharMethodA(this,clazz,method,args);
    }

    jShort CallStaticShortMethod(jclass clazz,
                                 jmethodID method, ...) {
        va_list args;
        jShort result;
        va_start(args,method);
        result = functions->CallStaticShortMethodV(this,clazz,method,args);
        va_end(args);
        return result;
    }
    jShort CallStaticShortMethodV(jclass clazz,
                                  jmethodID method, va_list args) {
        return functions->CallStaticShortMethodV(this,clazz,method,args);
    }
    jShort CallStaticShortMethodA(jclass clazz,
                                  jmethodID method, const jvalue *args) {
        return functions->CallStaticShortMethodA(this,clazz,method,args);
    }

    jint CallStaticIntMethod(jclass clazz,
                             jmethodID method, ...) {
        va_list args;
        jint result;
        va_start(args,method);
        result = functions->CallStaticIntMethodV(this,clazz,method,args);
        va_end(args);
        return result;
    }
    jint CallStaticIntMethodV(jclass clazz,
                              jmethodID method, va_list args) {
        return functions->CallStaticIntMethodV(this,clazz,method,args);
    }
    jint CallStaticIntMethodA(jclass clazz,
                              jmethodID method, const jvalue *args) {
        return functions->CallStaticIntMethodA(this,clazz,method,args);
    }

    jlong CallStaticLongMethod(jclass clazz,
                               jmethodID method, ...) {
        va_list args;
        jlong result;
        va_start(args,method);
        result = functions->CallStaticLongMethodV(this,clazz,method,args);
        va_end(args);
        return result;
    }
    jlong CallStaticLongMethodV(jclass clazz,
                                jmethodID method, va_list args) {
        return functions->CallStaticLongMethodV(this,clazz,method,args);
    }
    jlong CallStaticLongMethodA(jclass clazz,
                                jmethodID method, const jvalue *args) {
        return functions->CallStaticLongMethodA(this,clazz,method,args);
    }

    jFloat CallStaticFloatMethod(jclass clazz,
                                 jmethodID method, ...) {
        va_list args;
        jFloat result;
        va_start(args,method);
        result = functions->CallStaticFloatMethodV(this,clazz,method,args);
        va_end(args);
        return result;
    }
    jFloat CallStaticFloatMethodV(jclass clazz,
                                  jmethodID method, va_list args) {
        return functions->CallStaticFloatMethodV(this,clazz,method,args);
    }
    jFloat CallStaticFloatMethodA(jclass clazz,
                                  jmethodID method, const jvalue *args) {
        return functions->CallStaticFloatMethodA(this,clazz,method,args);
    }

    jDouble CallStaticDoubleMethod(jclass clazz,
                                   jmethodID method, ...) {
        va_list args;
        jDouble result;
        va_start(args,method);
        result = functions->CallStaticDoubleMethodV(this,clazz,method,args);
        va_end(args);
        return result;
    }
    jDouble CallStaticDoubleMethodV(jclass clazz,
                                    jmethodID method, va_list args) {
        return functions->CallStaticDoubleMethodV(this,clazz,method,args);
    }
    jDouble CallStaticDoubleMethodA(jclass clazz,
                                    jmethodID method, const jvalue *args) {
        return functions->CallStaticDoubleMethodA(this,clazz,method,args);
    }

    void CallStaticVoidMethod(jclass cls, jmethodID method, ...) {
        va_list args;
        va_start(args,method);
        functions->CallStaticVoidMethodV(this,cls,method,args);
        va_end(args);
    }
    void CallStaticVoidMethodV(jclass cls, jmethodID method,
                               va_list args) {
        functions->CallStaticVoidMethodV(this,cls,method,args);
    }
    void CallStaticVoidMethodA(jclass cls, jmethodID method,
                               const jvalue * args) {
        functions->CallStaticVoidMethodA(this,cls,method,args);
    }

    jfieldID GetStaticFieldID(jclass clazz, const char *name,
                              const char *sig) {
        return functions->GetStaticFieldID(this,clazz,name,sig);
    }
    jobject GetStaticObjectField(jclass clazz, jfieldID fieldID) {
        return functions->GetStaticObjectField(this,clazz,fieldID);
    }
    jBoolean GetStaticBooleanField(jclass clazz, jfieldID fieldID) {
        return functions->GetStaticBooleanField(this,clazz,fieldID);
    }
    jbyte GetStaticByteField(jclass clazz, jfieldID fieldID) {
        return functions->GetStaticByteField(this,clazz,fieldID);
    }
    jChar GetStaticCharField(jclass clazz, jfieldID fieldID) {
        return functions->GetStaticCharField(this,clazz,fieldID);
    }
    jShort GetStaticShortField(jclass clazz, jfieldID fieldID) {
        return functions->GetStaticShortField(this,clazz,fieldID);
    }
    jint GetStaticIntField(jclass clazz, jfieldID fieldID) {
        return functions->GetStaticIntField(this,clazz,fieldID);
    }
    jlong GetStaticLongField(jclass clazz, jfieldID fieldID) {
        return functions->GetStaticLongField(this,clazz,fieldID);
    }
    jFloat GetStaticFloatField(jclass clazz, jfieldID fieldID) {
        return functions->GetStaticFloatField(this,clazz,fieldID);
    }
    jDouble GetStaticDoubleField(jclass clazz, jfieldID fieldID) {
        return functions->GetStaticDoubleField(this,clazz,fieldID);
    }

    void SetStaticObjectField(jclass clazz, jfieldID fieldID,
                        jobject value) {
      functions->SetStaticObjectField(this,clazz,fieldID,value);
    }
    void SetStaticBooleanField(jclass clazz, jfieldID fieldID,
                        jBoolean value) {
      functions->SetStaticBooleanField(this,clazz,fieldID,value);
    }
    void SetStaticByteField(jclass clazz, jfieldID fieldID,
                        jbyte value) {
      functions->SetStaticByteField(this,clazz,fieldID,value);
    }
    void SetStaticCharField(jclass clazz, jfieldID fieldID,
                        jChar value) {
      functions->SetStaticCharField(this,clazz,fieldID,value);
    }
    void SetStaticShortField(jclass clazz, jfieldID fieldID,
                        jShort value) {
      functions->SetStaticShortField(this,clazz,fieldID,value);
    }
    void SetStaticIntField(jclass clazz, jfieldID fieldID,
                        jint value) {
      functions->SetStaticIntField(this,clazz,fieldID,value);
    }
    void SetStaticLongField(jclass clazz, jfieldID fieldID,
                        jlong value) {
      functions->SetStaticLongField(this,clazz,fieldID,value);
    }
    void SetStaticFloatField(jclass clazz, jfieldID fieldID,
                        jFloat value) {
      functions->SetStaticFloatField(this,clazz,fieldID,value);
    }
    void SetStaticDoubleField(jclass clazz, jfieldID fieldID,
                        jDouble value) {
      functions->SetStaticDoubleField(this,clazz,fieldID,value);
    }

    jstring NewString(const jChar *unicode, jSize len) {
        return functions->NewString(this,unicode,len);
    }
    jSize GetStringLength(jstring str) {
        return functions->GetStringLength(this,str);
    }
    const jChar *GetStringChars(jstring str, jBoolean *isCopy) {
        return functions->GetStringChars(this,str,isCopy);
    }
    void ReleaseStringChars(jstring str, const jChar *chars) {
        functions->ReleaseStringChars(this,str,chars);
    }

    jstring NewStringUTF(const char *utf) {
        return functions->NewStringUTF(this,utf);
    }
    jSize GetStringUTFLength(jstring str) {
        return functions->GetStringUTFLength(this,str);
    }
    const char* GetStringUTFChars(jstring str, jBoolean *isCopy) {
        return functions->GetStringUTFChars(this,str,isCopy);
    }
    void ReleaseStringUTFChars(jstring str, const char* chars) {
        functions->ReleaseStringUTFChars(this,str,chars);
    }

    jSize GetArrayLength(jarray array) {
        return functions->GetArrayLength(this,array);
    }

    jobjectArray NewObjectArray(jSize len, jclass clazz,
                                jobject init) {
        return functions->NewObjectArray(this,len,clazz,init);
    }
    jobject GetObjectArrayElement(jobjectArray array, jSize index) {
        return functions->GetObjectArrayElement(this,array,index);
    }
    void SetObjectArrayElement(jobjectArray array, jSize index,
                               jobject val) {
        functions->SetObjectArrayElement(this,array,index,val);
    }

    jbooleanArray NewBooleanArray(jSize len) {
        return functions->NewBooleanArray(this,len);
    }
    jbyteArray NewByteArray(jSize len) {
        return functions->NewByteArray(this,len);
    }
    jcharArray NewCharArray(jSize len) {
        return functions->NewCharArray(this,len);
    }
    jshortArray NewShortArray(jSize len) {
        return functions->NewShortArray(this,len);
    }
    jintArray NewIntArray(jSize len) {
        return functions->NewIntArray(this,len);
    }
    jlongArray NewLongArray(jSize len) {
        return functions->NewLongArray(this,len);
    }
    jfloatArray NewFloatArray(jSize len) {
        return functions->NewFloatArray(this,len);
    }
    jdoubleArray NewDoubleArray(jSize len) {
        return functions->NewDoubleArray(this,len);
    }

    jBoolean * GetBooleanArrayElements(jbooleanArray array, jBoolean *isCopy) {
        return functions->GetBooleanArrayElements(this,array,isCopy);
    }
    jbyte * GetByteArrayElements(jbyteArray array, jBoolean *isCopy) {
        return functions->GetByteArrayElements(this,array,isCopy);
    }
    jChar * GetCharArrayElements(jcharArray array, jBoolean *isCopy) {
        return functions->GetCharArrayElements(this,array,isCopy);
    }
    jShort * GetShortArrayElements(jshortArray array, jBoolean *isCopy) {
        return functions->GetShortArrayElements(this,array,isCopy);
    }
    jint * GetIntArrayElements(jintArray array, jBoolean *isCopy) {
        return functions->GetIntArrayElements(this,array,isCopy);
    }
    jlong * GetLongArrayElements(jlongArray array, jBoolean *isCopy) {
        return functions->GetLongArrayElements(this,array,isCopy);
    }
    jFloat * GetFloatArrayElements(jfloatArray array, jBoolean *isCopy) {
        return functions->GetFloatArrayElements(this,array,isCopy);
    }
    jDouble * GetDoubleArrayElements(jdoubleArray array, jBoolean *isCopy) {
        return functions->GetDoubleArrayElements(this,array,isCopy);
    }

    void ReleaseBooleanArrayElements(jbooleanArray array,
                                     jBoolean *elems,
                                     jint mode) {
        functions->ReleaseBooleanArrayElements(this,array,elems,mode);
    }
    void ReleaseByteArrayElements(jbyteArray array,
                                  jbyte *elems,
                                  jint mode) {
        functions->ReleaseByteArrayElements(this,array,elems,mode);
    }
    void ReleaseCharArrayElements(jcharArray array,
                                  jChar *elems,
                                  jint mode) {
        functions->ReleaseCharArrayElements(this,array,elems,mode);
    }
    void ReleaseShortArrayElements(jshortArray array,
                                   jShort *elems,
                                   jint mode) {
        functions->ReleaseShortArrayElements(this,array,elems,mode);
    }
    void ReleaseIntArrayElements(jintArray array,
                                 jint *elems,
                                 jint mode) {
        functions->ReleaseIntArrayElements(this,array,elems,mode);
    }
    void ReleaseLongArrayElements(jlongArray array,
                                  jlong *elems,
                                  jint mode) {
        functions->ReleaseLongArrayElements(this,array,elems,mode);
    }
    void ReleaseFloatArrayElements(jfloatArray array,
                                   jFloat *elems,
                                   jint mode) {
        functions->ReleaseFloatArrayElements(this,array,elems,mode);
    }
    void ReleaseDoubleArrayElements(jdoubleArray array,
                                    jDouble *elems,
                                    jint mode) {
        functions->ReleaseDoubleArrayElements(this,array,elems,mode);
    }

    void GetBooleanArrayRegion(jbooleanArray array,
                               jSize start, jSize len, jBoolean *buf) {
        functions->GetBooleanArrayRegion(this,array,start,len,buf);
    }
    void GetByteArrayRegion(jbyteArray array,
                            jSize start, jSize len, jbyte *buf) {
        functions->GetByteArrayRegion(this,array,start,len,buf);
    }
    void GetCharArrayRegion(jcharArray array,
                            jSize start, jSize len, jChar *buf) {
        functions->GetCharArrayRegion(this,array,start,len,buf);
    }
    void GetShortArrayRegion(jshortArray array,
                             jSize start, jSize len, jShort *buf) {
        functions->GetShortArrayRegion(this,array,start,len,buf);
    }
    void GetIntArrayRegion(jintArray array,
                           jSize start, jSize len, jint *buf) {
        functions->GetIntArrayRegion(this,array,start,len,buf);
    }
    void GetLongArrayRegion(jlongArray array,
                            jSize start, jSize len, jlong *buf) {
        functions->GetLongArrayRegion(this,array,start,len,buf);
    }
    void GetFloatArrayRegion(jfloatArray array,
                             jSize start, jSize len, jFloat *buf) {
        functions->GetFloatArrayRegion(this,array,start,len,buf);
    }
    void GetDoubleArrayRegion(jdoubleArray array,
                              jSize start, jSize len, jDouble *buf) {
        functions->GetDoubleArrayRegion(this,array,start,len,buf);
    }

    void SetBooleanArrayRegion(jbooleanArray array, jSize start, jSize len,
                               const jBoolean *buf) {
        functions->SetBooleanArrayRegion(this,array,start,len,buf);
    }
    void SetByteArrayRegion(jbyteArray array, jSize start, jSize len,
                            const jbyte *buf) {
        functions->SetByteArrayRegion(this,array,start,len,buf);
    }
    void SetCharArrayRegion(jcharArray array, jSize start, jSize len,
                            const jChar *buf) {
        functions->SetCharArrayRegion(this,array,start,len,buf);
    }
    void SetShortArrayRegion(jshortArray array, jSize start, jSize len,
                             const jShort *buf) {
        functions->SetShortArrayRegion(this,array,start,len,buf);
    }
    void SetIntArrayRegion(jintArray array, jSize start, jSize len,
                           const jint *buf) {
        functions->SetIntArrayRegion(this,array,start,len,buf);
    }
    void SetLongArrayRegion(jlongArray array, jSize start, jSize len,
                            const jlong *buf) {
        functions->SetLongArrayRegion(this,array,start,len,buf);
    }
    void SetFloatArrayRegion(jfloatArray array, jSize start, jSize len,
                             const jFloat *buf) {
        functions->SetFloatArrayRegion(this,array,start,len,buf);
    }
    void SetDoubleArrayRegion(jdoubleArray array, jSize start, jSize len,
                              const jDouble *buf) {
        functions->SetDoubleArrayRegion(this,array,start,len,buf);
    }

    jint RegisterNatives(jclass clazz, const JNINativeMethod *methods,
                         jint nMethods) {
        return functions->RegisterNatives(this,clazz,methods,nMethods);
    }
    jint UnregisterNatives(jclass clazz) {
        return functions->UnregisterNatives(this,clazz);
    }

    jint MonitorEnter(jobject obj) {
        return functions->MonitorEnter(this,obj);
    }
    jint MonitorExit(jobject obj) {
        return functions->MonitorExit(this,obj);
    }

    jint GetJavaVM(JavaVM **vm) {
        return functions->GetJavaVM(this,vm);
    }

    void GetStringRegion(jstring str, jSize start, jSize len, jChar *buf) {
        functions->GetStringRegion(this,str,start,len,buf);
    }
    void GetStringUTFRegion(jstring str, jSize start, jSize len, char *buf) {
        functions->GetStringUTFRegion(this,str,start,len,buf);
    }

    void * GetPrimitiveArrayCritical(jarray array, jBoolean *isCopy) {
        return functions->GetPrimitiveArrayCritical(this,array,isCopy);
    }
    void ReleasePrimitiveArrayCritical(jarray array, void *carray, jint mode) {
        functions->ReleasePrimitiveArrayCritical(this,array,carray,mode);
    }

    const jChar * GetStringCritical(jstring string, jBoolean *isCopy) {
        return functions->GetStringCritical(this,string,isCopy);
    }
    void ReleaseStringCritical(jstring string, const jChar *cstring) {
        functions->ReleaseStringCritical(this,string,cstring);
    }

    jweak NewWeakGlobalRef(jobject obj) {
        return functions->NewWeakGlobalRef(this,obj);
    }
    void DeleteWeakGlobalRef(jweak ref) {
        functions->DeleteWeakGlobalRef(this,ref);
    }

    jBoolean ExceptionCheck() {
        return functions->ExceptionCheck(this);
    }

    jobject NewDirectByteBuffer(void* address, jlong capacity) {
        return functions->NewDirectByteBuffer(this, address, capacity);
    }
    void* GetDirectBufferAddress(jobject buf) {
        return functions->GetDirectBufferAddress(this, buf);
    }
    jlong GetDirectBufferCapacity(jobject buf) {
        return functions->GetDirectBufferCapacity(this, buf);
    }
    jobjectRefType GetObjectRefType(jobject obj) {
        return functions->GetObjectRefType(this, obj);
    }

#endif /* __cplusplus */
};

typedef struct JavaVMOption {
    char *optionString;
    void *extraInfo;
} JavaVMOption;

typedef struct JavaVMInitArgs {
    jint version;

    jint nOptions;
    JavaVMOption *options;
    jBoolean ignoreUnrecognized;
} JavaVMInitArgs;

typedef struct JavaVMAttachArgs {
    jint version;

    char *name;
    jobject group;
} JavaVMAttachArgs;

/* These will be VM-specific. */

#define JDK1_2
#define JDK1_4

/* End VM-specific. */

struct JNIInvokeInterface_ {
    void *reserved0;
    void *reserved1;
    void *reserved2;

    jint (JNICALL *DestroyJavaVM)(JavaVM *vm);

    jint (JNICALL *AttachCurrentThread)(JavaVM *vm, void **penv, void *args);

    jint (JNICALL *DetachCurrentThread)(JavaVM *vm);

    jint (JNICALL *GetEnv)(JavaVM *vm, void **penv, jint version);

    jint (JNICALL *AttachCurrentThreadAsDaemon)(JavaVM *vm, void **penv, void *args);
};

struct JavaVM_ {
    const struct JNIInvokeInterface_ *functions;
#ifdef __cplusplus

    jint DestroyJavaVM() {
        return functions->DestroyJavaVM(this);
    }
    jint AttachCurrentThread(void **penv, void *args) {
        return functions->AttachCurrentThread(this, penv, args);
    }
    jint DetachCurrentThread() {
        return functions->DetachCurrentThread(this);
    }

    jint GetEnv(void **penv, jint version) {
        return functions->GetEnv(this, penv, version);
    }
    jint AttachCurrentThreadAsDaemon(void **penv, void *args) {
        return functions->AttachCurrentThreadAsDaemon(this, penv, args);
    }
#endif
};

#ifdef _JNI_IMPLEMENTATION_
#define _JNI_IMPORT_OR_EXPORT_ JNIEXPORT
#else
#define _JNI_IMPORT_OR_EXPORT_ JNIIMPORT
#endif
_JNI_IMPORT_OR_EXPORT_ jint JNICALL
JNI_GetDefaultJavaVMInitArgs(void *args);

_JNI_IMPORT_OR_EXPORT_ jint JNICALL
JNI_CreateJavaVM(JavaVM **pvm, void **penv, void *args);

_JNI_IMPORT_OR_EXPORT_ jint JNICALL
JNI_GetCreatedJavaVMs(JavaVM **, jSize, jSize *);

/* Defined by native libraries. */
JNIEXPORT jint JNICALL
JNI_OnLoad(JavaVM *vm, void *reserved);

JNIEXPORT void JNICALL
JNI_OnUnload(JavaVM *vm, void *reserved);

#define JNI_VERSION_1_1 0x00010001
#define JNI_VERSION_1_2 0x00010002
#define JNI_VERSION_1_4 0x00010004
#define JNI_VERSION_1_6 0x00010006
#define JNI_VERSION_1_8 0x00010008

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* !_JAVASOFT_JNI_H_ */